# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
    - master 
    - release/*
    
  pull_request:
    branches: 
    - master 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
  
    name: Build and run tests

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Say Hi!
        run: echo Hello, world!, Welcome to my action!

    # Checks-out current repository in ubuntu's file stsyem
      - name: Checkout current repository in macos file system
        uses: actions/checkout@v1

    # Setup JDK
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

    # Build the app
    #  - name: Build the app
    #    run: ./gradlew build
        
        
    # Run Unit Tests
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
        
    # Run UI Tests
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: If the job has failed
        if: ${{ failure() }}
        run: cat file:///Users/runner/work/Android-Jetpack-example/Android-Jetpack-example/app/build/reports/tests/testDebugUnitTest/index.html
        
        
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
            name: reports
            path: app/build/reports
            
  generate-apk:
    name: Generate apk
    runs-on: ubuntu-latest
    needs:
    - build-and-test
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk
            
            
    


        
        
        
        
        
        
        
